language: java 
jdk: 
    - openjdk12
before_install:
    - mvn validate 
    - mvn clean install 
install:
    - "mvn -N io.takari:maven:wrapper -Dmaven = 3.6.3
    - "./mvnwm--show-version --errors --batch-mode test-compile depdency:go-offline"
script: 
    - "mvn verify"
after_success:
    - mvn coveralls:report

#This is a comment to see if I can get it to build 
#even more comments
#testing more 


